name: test

on: [pull_request]

env:
  NODE_VERSION: 20

jobs:
  release:
    runs-on: ubuntu-latest
    name: Test Publish and Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Make value for the before option
        id: date-value
        uses: actions/github-script@v7
        with:
          script: |
            const dt = new Date()
            dt.setDate(dt.getDate() - 7)
            const beforeDate = dt.toLocaleDateString("ja-JP", {year: "numeric", month: "2-digit", day: "2-digit"}).replaceAll('/', '-')
            return beforeDate
          result-encoding: string
      - name: Prepare
        run: |
          # echo "${{ steps.date-value.outputs.result }}"
          npm i --before ${{ steps.date-value.outputs.result }}
          if [[ `git status --porcelain` ]]; then
            echo "- npm install results in changes!"
            exit 1
          fi
          npm test
          npm shrinkwrap
